"""Functional FDM mechanical-design helpers."""

from .materials import MaterialProfile, material_profile
from .assembly_checks import (
    MotionPose,
    check_access_envelope,
    check_assembly_insertion_path,
    check_assembly_interference,
    check_fastener_stack,
    check_linear_travel,
    check_rotational_motion_path,
    check_sampled_motion_path,
    check_tool_access,
)
from .model import (
    AssemblyCheckResult,
    AssemblyGraph,
    BridgeSpec,
    DesignBundle,
    DesignDelta,
    DesignDecision,
    DesignPart,
    DesignRecord,
    FeatureResult,
    Finding,
    FunctionalRequirement,
    InterfaceSpec,
    PrintPlan,
    ReferenceComponent,
    ReviewAnnotation,
    Severity,
    SourceRecord,
)
from .profile import FitProfile

__all__ = [
    "AssemblyCheckResult",
    "AssemblyGraph",
    "BridgeSpec",
    "DesignBundle",
    "DesignDelta",
    "DesignDecision",
    "DesignPart",
    "DesignRecord",
    "FeatureResult",
    "Finding",
    "FitProfile",
    "FunctionalRequirement",
    "InterfaceSpec",
    "PrintPlan",
    "ReferenceComponent",
    "ReviewAnnotation",
    "MaterialProfile",
    "MotionPose",
    "Severity",
    "SourceRecord",
    "material_profile",
    "check_access_envelope",
    "check_assembly_insertion_path",
    "check_assembly_interference",
    "check_fastener_stack",
    "check_linear_travel",
    "check_rotational_motion_path",
    "check_sampled_motion_path",
    "check_tool_access",
]
